#!/usr/bin/env bash
# commands to install nginx on web server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/ww/html/index.html

# testing nginx configurations
sudo nginx -t

sudo service nginx restart

sudo service nginx reload
