#!/usr/bin/env bash
# configures an nginx server to listen on port 80

# creates a symbolic link between nginx file and enabled sites dir
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminates the first nginx process ID
kill "$(grep 'nginx' | head -1)"
