#!/usr/bin/env bash
# a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
v=0
while [ $v -lt 10 ]
do
if [ $v -eq 9 ]
then
echo "Hi"
fi
echo "Best School"
((v++))
done
