#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
v=0
while [ $v -lt 10 ]
do
if [ $v -eq 3 ]
then
echo "bad luck"
elif [ $v -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
((v++))
done
