#!/usr/bin/env bash
# SSH client configuration


Host *
	passwordAuthentification no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPDelegateCredentials no
